billing/urls.py
from django.urls import path
from .views import EsewaPaymentRequest, EsewaVerification, KhaltiVerifyView, khalti_request_view

app_name = "billings"
urlpatterns = [
  path('Khalti_payment/',khalti_request_view, name='khalti'),
  path('Khalti_verify/',KhaltiVerifyView.as_view(), name='khaltiverify'),
  path('esewa_payment',EsewaPaymentRequest.as_view(),name='esewa_payment'),
  path('esewa_verification',EsewaVerification.as_view(),name='esewa_verify'),

]

carts/urls.py
from carts.views import (cart_detail_api_view, cart_home, cart_update, checkout_done_view, checkout_home)
from django.urls import path

app_name = "Carts"
urlpatterns = [
    path('',cart_home, name="home"),
    path('update', cart_update, name="update"),
    path('checkout/',checkout_home, name="checkout"),
    path('checkout/success',checkout_done_view, name="success"),
    path('api/cart/',cart_detail_api_view, name="cartApi"),    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from ecommerce import settings

from django.contrib.auth.views import LogoutView
from .views import about_page, contact_page, homepage
from accounts.views import LoginView,RegisterView,guest_register_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage, name="homepage"),
    path('about/',about_page,name="about"),
    path('contact/',contact_page,name="contact"),
    path('login/',LoginView.as_view(),name="login"),
    path('register/',RegisterView.as_view(),name="register"),
    path('logout',LogoutView.as_view(), name="logout"),
    path('register/guest',guest_register_view,name="guest_register"),
    path('products/',include('products.urls', namespace="products")),
    path('search/',include('search.urls', namespace="Search")),
    path('cart/',include('carts.urls', namespace="Carts")),
    path('accounts/',include('accounts.urls', namespace='Accounts')),
    path('accounts/',include('accounts.password.urls')),
    path('',include('addresses.urls',namespace="Addresses")),
    path('billing/',include('billing.urls',namespace="billings")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing/models.py
from accounts.models import GuestEmail
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save, pre_save
User = settings.AUTH_USER_MODEL



class BillingProfileManager(models.Manager):
    def get_or_new(self, request):
        user = request.user
        guest_email_id = request.session.get('guest_email_id')
        obj=None
        created=False
        if user.is_authenticated:
            # Logged in checkout
            obj, created = self.model.objects.get_or_create(user=user,email=user.email)
        elif guest_email_id is not None:
            # Guest user checkout
            guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
            obj, created = self.model.objects.get_or_create(email=guest_email_obj.email)
        else:
            pass
        return obj, created


class BillingProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)
    email = models.EmailField()
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = BillingProfileManager()

    def __str__(self):
        return self.email


# def billing_profile_created_receiver(sender, instance, *args, **kwargs):
#     if not instance.customer_id and instance.email:
#         customer = stripe.Customer.create(
#             email=instance.email
#         )
#         print(customer)
#         instance.customer_id = customer.id

# pre_save.connect(billing_profile_created_receiver,sender = BillingProfile)

def user_created_receiver(sender, instance, created, *args, **kwargs):
    if created:
        BillingProfile.objects.get_or_create(user=instance, email=instance.email)

post_save.connect(user_created_receiver,sender=User)

billing/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render,redirect
from django.urls import reverse
from orders.models import Order
from django.views import View
import requests
# Create your views here.

def khalti_request_view(request):
    o_id = request.GET.get('o_id')
    order_obj = Order.objects.get(order_id=o_id)
    context={
        'order':order_obj
    }
    return render(request,'billing/khalti_payment.html',context)

class KhaltiVerifyView(View):
    def post(self,request,*args, **kwargs):
        token = request.POST.get('token')
        amount = request.POST.get('amount')
        o_id = request.POST.get('order_id')

        
        url = "https://khalti.com/api/v2/payment/verify/"
        payload = {
        "token": token,
        "amount": amount
        }
        headers = {
        "Authorization": "Key test_secret_key_f59e8b7d18b4499ca40f68195a846e9b"    
        }    # your merchant key(live or test) provided by khalti

        response = requests.post(url, payload, headers = headers)
        res = response.json()
        if res.get('idx'):
            success = True
            order_obj = Order.objects.get(order_id = o_id)
            order_obj.payment_method = "Khalti"
            if order_obj.check_done():
                order_obj.mark_paid()
                request.session['cart_items'] = 0
                del request.session['cart_id']

        data = {
            'success':success
        }
        return JsonResponse(data)

class EsewaPaymentRequest(View):
    def get(self, request, *args, **kwargs):
        o_id = request.GET.get('o_id')
        order_obj = Order.objects.get(order_id=o_id)
        context={
            'order':order_obj
        }
        return render(request,'billing/esewa_payment.html',context)


class EsewaVerification(View):
    def get(self, request, *args, **kwargs):
        o_id = request.GET.get('oid')
        amt = request.GET.get('amt')
        refId = request.GET.get('refId')
        print(o_id,amt,refId)

        url ="https://uat.esewa.com.np/epay/transrec"
        d = {
            'amt': amt,
            'scd': 'EPAYTEST',
            'rid': refId,
            'pid':o_id,
        }
        resp = requests.post(url, d)
        if str(resp.text).find('success'):
            order_obj = Order.objects.get(order_id = o_id)
            order_obj.payment_method = 'Esewa'
            if order_obj.check_done():
                    order_obj.mark_paid()
                    request.session['cart_items'] = 0
                    del request.session['cart_id']
            return redirect(reverse('Carts:success'))
        else:
            return HttpResponse('Error')
            

templates/billing/esewa_payment.html
{% extends "includes/base.html" %}

{% block content %}
    <div class="row">
        <div class='col-6 col-sm-6 col-md-6 col-lg-6'>
            <dl>
                <dt>
                    Order Id:
                </dt>
                <dd>
                    {{order.order_id}}
                </dd>
                <dt>
                    Shipping Address:
                </dt>
                <dd>
                    {{order.shipping_address.get_address}}
                </dd>
                <dt>
                    Billing Address:
                </dt>
                <dd>
                    {{order.billing_address.get_address}}
                </dd>
                <dt>Cart Items:</dt>
                    {% for product in order.cart.products.all %}
                        <dt>{{product}}</dt>
                    {% endfor %} 
                <dt>Cart Total:</dt>
                <dd>{{order.cart.total}}</dd>
                <dt>Shipping Total:</dt>
                    <dd>{{ order.shipping_total }}</dd>

                <dt>Total:</dt>
                <dd>{{order.total}}</dd>
            </dl>
        </div>
        <div class='col-6 col-sm-6 col-md-6 col-lg-6 mb-3'>
            <form action="https://uat.esewa.com.np/epay/main" method="POST">
                <div class="form-group">
                    <label for="pid">Order Id:</label>
                    <input value="{{order.order_id}}" name="pid" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="amt">Amount:</label>
                    <input value="{{order.cart.total}}" name="amt" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="txAmt">Tax Amount:</label>
                    <input value="0" name="txAmt" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="psc">Product Service Charge</label>
                    <input value="0" name="psc" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="pdc">Product Delivery Charge:</label>
                    <input value="{{order.shipping_total}}" name="pdc" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="scd">Merchant service code</label>
                    <input value="EPAYTEST" name="scd" type="text" class="form-control">
                </div>
                <div class="form-group d-none d-lg-none d-md-none d-sm-none">
                    <label for="url">Urls:</label>
                    <input value="http://127.0.0.1:8000{% url 'billings:esewa_verify' %}" type="text" name="su" class="form-control">
                    <input value="{{ request.build_absolute_uri }}" type="text" name="fu" class="form-control">
                </div>
                <div class="form-group">
                    <label for="tAmt">Total Amount:</label>
                    <input value="{{order.total}}" name="tAmt" type="text" class="form-control">
                </div>
                <input value="Submit" type="submit" class="btn btn-outline-primary">
            </form>
        </div>
    </div>

{% endblock %}

templates/billing/khalti_payment.html
{% extends "includes/base.html" %}

{% block content %}
    <dl>
        <dt>
            Order Id:
        </dt>
        <dd>
            {{order.order_id}}
        </dd>
        <dt>
            Shipping Address:
        </dt>
        <dd>
            {{order.shipping_address.get_address}}
        </dd>
        <dt>
            Billing Address:
        </dt>
        <dd>
             {{order.billing_address.get_address}}
        </dd>
        <dt>Cart Items:</dt>
            {% for product in order.cart.products.all %}
                <dt>{{product}}</dt>
            {% endfor %} 
        <dt>Cart Total:</dt>
        <dd>{{order.cart.total}}</dd>
        <dt>Shipping Total:</dt>
            <dd>{{ order.shipping_total }}</dd>

        <dt>Total:</dt>
        <dd>{{order.total}}</dd>


    </dl>
    

    
    
   
    <!-- Place this where you need payment button -->
    <button id="payment-button">Pay with Khalti</button>
    <!-- Place this where you need payment button -->
    <!-- Paste this code anywhere in you body tag -->
    
    <!-- Paste this code anywhere in you body tag -->
<!-- Khalti Script -->
{% if request.resolver_match.url_name == 'khalti' %}
<script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>
<script>
        var config = {
            // replace the publicKey with yours
            "publicKey": "test_public_key_dc74e0fd57cb46cd93832aee0a390234",
            "productIdentity": "order_{{order.order_id}}",
            "productName": "Dragon",
            "productUrl": "http://localhost:8000",
            "paymentPreference": [
                "KHALTI",
                "SCT",
                ],
            "eventHandler": {
                onSuccess (payload) {
                    // hit merchant api for initiating verfication
                    axios.post('{% url 'billings:khaltiverify' %}',{
                        token: payload.token,
                        amount: payload.amount,
                        order_id: {{order.order_id}}
                    }).then(function(res){
                        console.log(res.data)
                        if (res.data.success == true){
                            $.alert({
                                title: "Payment Successfull",
                                content: "Thank you for Shopping. Please visit us again.",
                                theme: "modern",
				                })
                                location.href('/')
                        }
                        else{
                            $.alert({
                                title: "Error Occurred",
                                content: "Please try again after a while. sorry for your in convinence.",
                                theme: "modern",
				                })
                            location.href('{{ request.build_absolute_uri }}')
                        }
                    })
                    //console.log(payload);
                },
                onError (error) {
                    console.log(error);
                },
                onClose () {
                    console.log('widget is closing');
                }
            }
        };

        var checkout = new KhaltiCheckout(config);
        var btn = document.getElementById("payment-button");
        btn.onclick = function () {
            // minimum transaction amount must be 10, i.e 1000 in paisa.
            checkout.show({amount: {{order.total}} *100 });
        }
    </script>
{% endif %}

{% endblock  %}