addresses/urls.py
from addresses.views import checkout_address_create_view, checkout_address_use_view
from django.urls import path

app_name="Addresses"
urlpatterns = [
    path('checkout/address/create',checkout_address_create_view,name="checkout_address_create"),
    path('checkout/address/reuse',checkout_address_use_view,name="checkout_address_reuse"),
]

carts/urls.py
from carts.views import (cart_detail_api_view, cart_home, cart_update, checkout_done_view, checkout_home)
from django.urls import path

app_name = "Carts"
urlpatterns = [
    path('',cart_home, name="home"),
    path('update', cart_update, name="update"),
    path('checkout/',checkout_home, name="checkout"),
    path('checkout/success',checkout_done_view, name="success"),
    path('api/cart/',cart_detail_api_view, name="cartApi"),    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from ecommerce import settings

from django.contrib.auth.views import LogoutView
from .views import about_page, contact_page, homepage
from accounts.views import LoginView,RegisterView,guest_register_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage, name="homepage"),
    path('about/',about_page,name="about"),
    path('contact/',contact_page,name="contact"),
    path('login/',LoginView.as_view(),name="login"),
    path('register/',RegisterView.as_view(),name="register"),
    path('logout',LogoutView.as_view(), name="logout"),
    path('register/guest',guest_register_view,name="guest_register"),
    path('products/',include('products.urls', namespace="products")),
    path('search/',include('search.urls', namespace="Search")),
    path('cart/',include('carts.urls', namespace="Carts")),
    path('accounts/',include('accounts.urls', namespace='Accounts')),
    path('accounts/',include('accounts.password.urls')),
    path('',include('addresses.urls',namespace="Addresses")),
    path('billing/',include('billing.urls',namespace="billings")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.conf import settings
from products.models import Product

from django.db.models.signals import pre_save,post_save,m2m_changed


User =settings.AUTH_USER_MODEL

# Create your models here.
class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id",None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count()==1:
            new_obj=False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj=True
            request.session["cart_id"] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)



class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,blank=True)
    products =  models.ManyToManyField(Product,blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00,max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects=CartManager()

    def __str__(self):
        return str(self.id)
    

def m2m_changed_cart_receiver(sender, instance,action, *args, **kwargs):
    if action == "post_add" or action == "post_remove" or action == "post_clear":
        products = instance.products.all()
        total = 0
        for product in products:
            total += product.price
        if instance.subtotal !=total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender = Cart.products.through) 


def pre_save_cart_receiver(sender, instance,*args, **kwargs):
    if instance.subtotal>0:
        instance.total = float(instance.subtotal) * float(1.08)
    else:
        instance.total = 0.00
pre_save.connect(pre_save_cart_receiver,sender=Cart)

carts/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.urls import reverse

from accounts.models import GuestEmail
from carts.models import Cart
from addresses.models import Address
from billing.models import BillingProfile
from orders.forms import PaymentMethods
from products.models import Product
from orders.models import Order

from addresses.forms import AddressForm
from accounts.forms import GuestForm, LoginForm
# Create your views here.
def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    # products =[]
    # for x in cart_obj.products.all():
    #     products.append({
    #         "name":x.name,
    #         "price":x.price,
    #     })
    products = [{"id":x.id,"name":x.title,"price":x.price,"url":x.get_absolute_url()}for x in cart_obj.products.all()]    # similar to above code
    data = {
        "products":products,
        "subTotal":cart_obj.subtotal,
        "total":cart_obj.total
    }
    return JsonResponse(data)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request,"carts/home.html",{"cart":cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id' or None)
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            return redirect("Carts:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            if cart_obj.total==0:
                print(f"cart_id = { request.session['cart_id'] }")
                Cart.objects.get(id= request.session['cart_id']).delete()
            added=False
        else:     
            cart_obj.products.add(product_obj)
            added=True
        count = cart_obj.products.count()
        request.session["cart_items"] = count
        if request.is_ajax():
            jsonData = {
                "added": added,
                "removed": not added,
                "cart_items": count
            }
            return JsonResponse(jsonData)
    return redirect("Carts:home")

def checkout_home(request):
    cart_obj, new_cart = Cart.objects.new_or_get(request)
    order_obj=None

    if new_cart or cart_obj.products.count()==0:
        return redirect('Carts:home')
    
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    method_form = PaymentMethods()

    billing_address_id = request.session.get("billing_address_id",None)
    shipping_address_id = request.session.get("shipping_address_id",None)


    billing_profile, billing_profile_created = BillingProfile.objects.get_or_new(request)
    address_qs = None
    # above logic
    # user = request.user
    # billing_profile=None
    # guest_email_id = request.session.get('guest_email_id')
    # if user.is_authenticated:
    #     # Logged in checkout
    #     billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(user=user,email=user.email)
    # elif guest_email_id is not None:
    #     # Guest user checkout
    #     guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
    #     billing_profile, billing_guest_profile_created = BillingProfile.objects.get_or_create(email=guest_email_obj.email)
    # else:
    #     pass
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.get_or_new(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
        if billing_address_id or shipping_address_id:
            order_obj.save()
        
    if request.method == "POST":
        method = request.POST.get('payment_method')
        
        if method == 'Cash on Delivery':
            is_done = order_obj.check_done()
            if is_done:
                order_obj.payment_method = method
                order_obj.mark_shipped()
                request.session['cart_items'] = 0
                del request.session["cart_id"]
                return redirect("Carts:success")
        elif method == 'Khalti':
            return redirect(reverse('billings:khalti')+"?o_id="+str(order_obj.order_id))
        elif method == 'Esewa':
            return redirect(reverse('billings:esewa_payment') + "?o_id=" + str(order_obj.order_id))
        # order_qs = Order.objects.filter(billing_profile=billing_profile,cart=cart_obj,active=True)
        # if order_qs.count()==1:
        #     order_obj = order_qs.first()
        # else:
        #     # old_order_qs = Order.objects.exclude(billing_profile=billing_profile).filter(cart=cart_obj, active=True)
        #     # if old_order_qs.exists():
        #     #     old_order_qs.update(active=False)  
        #     order_obj = Order.objects.create(billing_profile=billing_profile,cart=cart_obj)

    context = {
        "order":order_obj,
        "billing_profile":billing_profile,
        "login_form":login_form,
        "guest_form":guest_form,
        "address_form":address_form,
        "address_qs":address_qs,
        "method_form":method_form
    }
    return render(request,'carts/checkout.html',context)


def checkout_done_view(request):
    return render(request,'carts/checkout_done.html')

templates/carts/checkout.html
{% extends 'includes/base.html' %}
{% block content %}
<h1>Checkout</h1>
{% if not billing_profile %}
    <div class="row" >
        <div class="col-12 col-md-6">
            {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
        </div>
        <div class="col-12 col-md-6" >
            Continue as a Guest
            {% url "guest_register" as guest_register_url %}
            {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
        </div>
    </div>
{% else %}
    {% if not order.shipping_address  %}
        <div class ="row">
            <div class="col-md-12 col-12">
                <h2>Shipping Address</h2>
                     <hr>
            </div>
            <div class="col-md-6">
                {% url "Addresses:checkout_address_create" as checkout_address_create %}
                {% include 'addresses/snippets/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type="shipping"  %}
            </div> 
            <div class="col-md-6 col-6">
                {% url 'Addresses:checkout_address_reuse' as checkout_address_reuse %}
                {% include 'addresses/snippets/prev_address.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type="shipping" action_url=checkout_address_reuse  %}
            </div>
        </div>
    {% elif not order.billing_address %}
        <div class ="row">
                <div class="col-12">
                    <p class="lead">Billing Address</p>
                    <hr>
                </div>
                <div class="col-md-6 col-6">
                    
                    {% url "Addresses:checkout_address_create" as checkout_address_create %}
                    {% include 'addresses/snippets/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type="billing"  %}
                </div>
                <div class="col-md-6 col-6">
                    {% url 'Addresses:checkout_address_reuse' as checkout_address_reuse %}
                    {% include 'addresses/snippets/prev_address.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type="billing" action_url=checkout_address_reuse %}
                </div>  
        </div>
    {% else %}
        <dl>
            <dt class="text-info fa-2x" >Finalize Checkout</dt>
            <dt>Cart Items:</dt>
                {% for product in order.cart.products.all %}
                    <dd>{{ product }} - {{product.price}} </dd> {% if not forloop.last %} <br> {% endif %}
                {% endfor %}
            <dt>Shipping Address</dt>
                <dt>{{ order.shipping_address.get_address }}</dt>
            <dt>Billing Address</dt>
                <dt>{{ order.billing_address.get_address }}</dt>
            <dt>Cart Total:</dt>
                <dd>{{ order.cart.total }}</dd>
            <dt>Shipping Total:</dt>
                <dd>{{order.shipping_total}}</dd>
            <dt>Order Total:</dt>
                <dd>{{order.total}}</dd>
        </dl>
        <hr>
        <h3>Pay with:</h3>
        <form class="form" action="" method="POST">
            {% csrf_token %}
            {{method_form.as_p}}
            <button type="submit" class="btn btn-outline-success" >Proceed to pay</button>                
        </form> 
    {% endif %}

{% endif %}
{% endblock  %}

templates/carts/checkout_done.html
{% extends 'includes/base.html' %}

{% block content %}
<div class="col-6 mx-auto">
    <h1 class="display-1">
        Thank you for your order!!!.
    </h1>
</div>

{% endblock  %}

templates/carts/home.html
{% extends 'includes/base.html' %}
{% block content %}
<h1>Cart</h1>
{% if cart.products.exists %}
<table class="table cart-table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody class='cart-body'>

    {% for product in cart.products.all %}
      <tr class='cart-product'>
        <th scope="row" id='{{forloop.counter}}'>{{ forloop.counter }}</th>
        <td><a href="{{ product.get_absolute_url }}">{{product.title}}</a>  
        {% include 'carts/snippets/remove_product.html' with product_id=product.id%} 
        </td>
        <td>$ {{ product.price }}</td>
      </tr>
    {% endfor %}

 
  <tr>
      <th colspan="2" class="text-center">Sub Total</th>
      <td><b>$ <span class='cart-sub-total'>{{ cart.subtotal }}</span></b>  </td>
    </tr>
    <tr>
      <th colspan="2"class="text-center" ><b>Total</b></th>
      <td> <b>$ <span class='cart-total'>{{ cart.total }}</span> </b></td>
    </tr>
    <tr>
      <th colspan="2" class="text-center" >
      <a href="{% url 'Carts:checkout' %}" class="btn btn-success">Checkout</a></th>
    </tr>
  </tbody>
</table>
<div class='cart-product-remove-form d-none'>
{% include 'carts/snippets/remove_product.html' %}
</div>
{% else %}
    <p class="lead">Cart is empty  </p>
{% endif %}

{% endblock  %}